{% set name = "atlassian-python-api" %}
{% set version = "3.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: acd9a0e66ca56f403df2f047bd7efde1271fd7842a7382ed82db2ebaae72d3c5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - deprecated
    - oauthlib
    - python >=2.7
    - requests
    - requests-oauthlib
    - six

test:
  imports:
    - atlassian
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/atlassian-api/atlassian-python-api
  summary: Python Atlassian REST API Wrapper
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbast
    - epilif1017a
